/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.io.File;
import javax.swing.JFileChooser;
import mic1.arqcomp.ufc.Mic1ArqCompUFC;

/**
 *
 * @author LaNo
 */
public class ConfigAC extends javax.swing.JDialog {

    /**
     * Creates new form ConfigAC
     */
    public int ac;
    public boolean altera = false;
    public String memoria = null;
    public String caminhoDoArqAC = null;
    public String caminhoArqMem = null;
    private final String txtPadraoArquivo = "Nenhum arquivo selecionado";
    
    public ConfigAC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.lbNomeArquivo.setText(txtPadraoArquivo);
        this.lbNomeArqMem.setText(txtPadraoArquivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMemRam = new javax.swing.JTextField();
        btnCarregarMemAC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbArmCont = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSelArq = new javax.swing.JButton();
        lbNomeArquivo = new javax.swing.JLabel();
        btnSelArqMem = new javax.swing.JButton();
        lbNomeArqMem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        jLabel2.setText("Configuração");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel4.setText("Memória Principal");

        txtMemRam.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtMemRam.setText("0000000100000001000000110000000100000100000001100000000000000000");

        btnCarregarMemAC.setBackground(new java.awt.Color(204, 255, 204));
        btnCarregarMemAC.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        btnCarregarMemAC.setForeground(new java.awt.Color(102, 0, 102));
        btnCarregarMemAC.setText("Alterar");
        btnCarregarMemAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarMemACActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 14)); // NOI18N
        jLabel1.setText("Selecione o Armazenamento de Controle");

        cbArmCont.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        cbArmCont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula 9", "Aula 10" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("INSTRUÇÕES");

        jLabel5.setText("Selecione o Armazenamento de Controle pela aula do professor ou escolha um arquivo");

        jLabel6.setText("Insira um valor em binário na Memória Principal ou selecione um arquivo");

        jLabel7.setText("Clique em Alterar");

        btnSelArq.setText("Selecionar Arquivo");
        btnSelArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelArqActionPerformed(evt);
            }
        });

        lbNomeArquivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnSelArqMem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelArqMem.setText("Selecione arq");
        btnSelArqMem.setBorderPainted(false);
        btnSelArqMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelArqMemActionPerformed(evt);
            }
        });

        lbNomeArqMem.setForeground(new java.awt.Color(255, 0, 0));
        lbNomeArqMem.setText("Sem arquivo selecionado");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("OU");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("OU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSelArq)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cbArmCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarregarMemAC))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbNomeArquivo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSelArqMem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15)
                        .addComponent(txtMemRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNomeArqMem)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelArqMem)
                    .addComponent(txtMemRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomeArqMem)
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelArq)
                    .addComponent(btnCarregarMemAC)
                    .addComponent(cbArmCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addComponent(lbNomeArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarMemACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarMemACActionPerformed
        this.memoria = this.txtMemRam.getText();
        this.ac = this.cbArmCont.getSelectedIndex();
        this.altera = true;
    }//GEN-LAST:event_btnCarregarMemACActionPerformed

    private void btnSelArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelArqActionPerformed
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1) {
            this.caminhoDoArqAC = null;
            this.lbNomeArquivo.setText(txtPadraoArquivo);
        }
        else {
           File arquivo = file.getSelectedFile();
           this.caminhoDoArqAC = arquivo.getPath();
           this.lbNomeArquivo.setText(arquivo.getName());
           //System.out.println(arquivo.getPath());
           //System.out.println(arquivo.getName());
        }
    }//GEN-LAST:event_btnSelArqActionPerformed

    private void btnSelArqMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelArqMemActionPerformed
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1) {
            this.caminhoArqMem = null;
            this.lbNomeArqMem.setText(txtPadraoArquivo);
        }
        else {
           File arquivo = file.getSelectedFile();
           this.caminhoArqMem = arquivo.getPath();
           this.lbNomeArqMem.setText(arquivo.getName());
        }
    }//GEN-LAST:event_btnSelArqMemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigAC dialog = new ConfigAC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarMemAC;
    private javax.swing.JButton btnSelArq;
    private javax.swing.JButton btnSelArqMem;
    private javax.swing.JComboBox<String> cbArmCont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbNomeArqMem;
    private javax.swing.JLabel lbNomeArquivo;
    private javax.swing.JTextField txtMemRam;
    // End of variables declaration//GEN-END:variables
}
